spring:
  application:
    name: spring-data-rest
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:7000/spring-data-rest
    username: root
    password: sibi@soft
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
server:
  port: 7100
